<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyVersion>1.8.1.0</AssemblyVersion>
    <FileVersion>1.8.1.0</FileVersion>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avalanche.Engine\Avalanche.Engine.csproj" />
  </ItemGroup>

</Project>
